import blindspot from './images/blindspot.jpg';
import cabinstay from './images/cabinstay.jpg';
import skyfall from './images/skyfall.jpg';
import deadpool from './images/deadpool.jpg';
import scorpion from './images/scorpion.jpg';
import scarface from './images/scarface.jpg';

  export default function getGallery() {
    return [
      { id: 'blind', name:'BLIND SPOT', logo: blindspot, details:'Blindspot is an American crime drama television series created by Martin Gero, starring Sullivan Stapleton and Jaimie Alexander. Blindspot focuses on a mysterious tattooed woman who is found naked inside a travel bag in Times Square by the FBI, with no recollection of her own past or identity. They discover that her tattoos contain clues to crimes they will have to solve.' },
      { id: 'scorpion', name: 'SCORPION', logo: scorpion, details:'Scorpion (stylized as </SCORPION>) is an American action drama television series created by Nick Santora for CBS. The series stars Elyes Gabel, Katharine McPhee, Eddie Kaye Thomas, and Jadyn Wong, among others. Loosely based on the life of its executive producer and self-proclaimed computer expert Walter Brien,the series centers on Brien and his friends helping to solve complex global problems and save livesScorpion is said to be the last line of defense against complex, high-tech threats around the globe. Drawing on a diverse set of skills and experience such as coding, psychology, and engineering, they are able to solve these situations. The team tackles a variety of problems, many of which are extremely complicated. While they are frequently called into service by the Department of Homeland Security, they also accept work from private individuals and organizations.' },
      { id: 'skarface', name:'SCARFACE', logo: scarface, details:'Scarface is a 1983 American crime film directed by Brian De Palma and written by Oliver Stone, a remake of the 1932 film of the same name.The film tells the story of Cuban refugee Tony Montana (Al Pacino) who arrives in 1980s Miami with nothing and rises to become a powerful drug kingpin. The cast also features Michelle Pfeiffer, Steven Bauer, Robert Loggia, F. Murray Abraham and Mary Elizabeth Mastrantonio.' },
      { id: 'deadpool', name:'DEAD POOL', logo: deadpool, details:'Deadpool is a 2016 American superhero film based on the Marvel Comics character of the same name, distributed by 20th Century Fox. It is the eighth installment of the X-Men film series and the first standalone Deadpool film. Directed by Tim Miller from a screenplay by Rhett Reese and Paul Wernick, the film stars Ryan Reynolds as Wade Wilson / Deadpool alongside Morena Baccarin, Ed Skrein, T. J. Miller, Gina Carano and Brianna Hildebrand. In the film, Wilson—as the antihero Deadpool—hunts down the man who gave him mutant abilities and caused his scarred physical appearance.'},
      { id: 'cabinstay', name: 'CABIN STAY', logo: cabinstay, details:'An Interactive Virtual Reality film. A group of childhood friends barricade themselves in a strangers cabin while escaping a killer. During the course of the night, it seems a more elaborate plot is at play.'},
      { id: 'skyfall', name:'SKYFALL', logo: skyfall, details:'Skyfall is a 2012 spy film, the twenty-third in the James Bond series produced by Eon Productions. The film is the third to star Daniel Craig as the fictional MI6 agent James Bond and features Javier Bardem as Raoul Silva, the villain. It was directed by Sam Mendes and written by Neal Purvis, Robert Wade, and John Logan, and features the theme song "Skyfall", written and performed by Adele. It was distributed by Metro-Goldwyn-Mayer (MGM) and Columbia Pictures'}
    ];   
  }